accounts/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
  
    path('', include('django.contrib.auth.urls')),
    path('register/' , views.register , name="register"),
    path('v1/token/' , jwt_views.TokenObtainPairView.as_view() , name="token_obtain_pair"),
    path("v1/refresh/" ,jwt_views.TokenRefreshView.as_view() , name="token_refresh"),
    path('v1/register/',  include('rest_auth.registration.urls')),

]

backend/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("api/", include('accounts.urls')),
    path('newjob/',include('newjob.urls'))
]

newjob/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create', views.create, name="create.newjob"), #localhost:8000/newjob/create
    path('read', views.read, name="read.newjob"), #localhost:8000/newjob/read
    path('update/<int:job_id>', views.update, name="update.newjob"), #localhost:8000/newjob/update/id
    path('delete/<int:job_id>', views.delete, name="delete.newjob"), #localhost:8000/newjob/delete/id
]

accounts/models.py
from django.db import models

# Create your models here.

newjob/models.py
from django.db import models

# Create your models here.

class Newjob(models.Model):
    title = models.CharField(max_length=100, null=False)
    type = models.CharField(max_length=100, null=False)
    background = models.TextField()
    price = models.DecimalField(max_digits= 15, decimal_places=3, null=False)
    image = models.ImageField(upload_to='static/newjob/images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

newjob/forms.py
from django import forms
from .models import Newjob

class NewjobForm(forms.ModelForm):

    class Meta:
        model = Newjob
        fields = ['title', 'type', 'background', 'price', 'image']

accounts/views.py
 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render

# Create your views here.


def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = UserCreationForm()

    return render(request, 'registration/register.html', {'form': form})

newjob/views.py
from django.shortcuts import render, redirect
from .forms import NewjobForm
from .models import Newjob


# Create your views here.
def create(request):
    if request.method == "POST":
        form = NewjobForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('read.newjob')
    return render(request, 'job/create.html')


def read(request):
    jobs = Newjob.objects.all()
    return render(request, 'job/read.html', {'jobs': jobs})


def update(request, job_id):
    job = Newjob.objects.get(id=job_id)
    if request.method == "POST":
        form = NewjobForm(request.POST, request.FILES, instance=job)
        if form.is_valid():
            form.save()
            return redirect('read.newjob')
    return render(request, 'job/update.html', {'job': job})


def delete(request, job_id):
    job = Newjob.objects.get(id=job_id)
    job.delete()
    return redirect('read.newjob')

accounts/templates/main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script defer src="{% static 'fontawesome/js/all.min.js' %}"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>




{% block content %}

{% endblock %}


    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

newjob/templates/job/create.html
{% extends 'base.html' %}

{% block content %}

    <h1>ثبت کار</h1>
    <form class="form-group" action="{% url 'create.newjob' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="container">
            <label for="id_title">عنوان:
                <input class="form-control" type="text" name="title" id="id_title" placeholder="عنوان...">
            </label>
            <br>
            <label for="id_name">نوع:
                <input class="form-control" type="text" name="type" id="id_name" placeholder="نوع...">
            </label>
            <br>
            <label for="id_describe">رزومه مورد نیاز:
                <textarea class="form-control" type="text" name="background" id="id_describe" placeholder="رزومه مورد نیاز..."></textarea>
            </label>
            <br>
            <label for="id_price">حقوق:
                <input class="form-control" type="number" min="0" name="price" id="id_price" placeholder="حقوق...">
            </label>
            <br>
            <label for="id_image">عکس:
                <input class="form-control" type="file" name="image" id="id_image">
            </label>
            <br>
            <input class="btn btn-success" type="submit" value="ثبت">
        </div>
    </form>

{% endblock %}

newjob/templates/job/read.html
{% extends 'base.html' %}

{% block content %}

    <h2>کار ها</h2>
    <a class="btn btn-success mt-2" href="{% url 'create.newjob' %}">کار جدید</a>
      <div class="table-responsive mt-3">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>عنوان</th>
              <th>نوع</th>
              <th>قیمت</th>
              <th>عکس</th>
              <th>تاریخ ساخت</th>
              <th>تاریخ ویرایش</th>
              <th>عملیات</th>
            </tr>
          </thead>
          <tbody>

          {% for job in jobs %}
            <tr>
              <td>{{ job.title }}</td>
              <td>{{ job.type }}</td>
              <td>{{ job.price }}</td>
              <td>
                  <img src="/{{ job.image }}" width="75" height="75" alt="T_T">
              </td>
              <td>{{ job.created_at }}</td>
              <td>{{ job.updated_at }}</td>
              <td>
                  <a class="btn btn-warning" href="{% url 'update.newjob' job.id %}">ویرایش</a>
                  <a class="btn btn-danger" href="{% url 'delete.newjob' job.id  %}">حذف</a>
              </td>

            </tr>

          {% endfor %}

          </tbody>
        </table>
      </div>

{% endblock %}

newjob/templates/job/update.html
{% extends 'base.html' %}

{% block content %}

    <h1>ویرایش کار</h1>
    <form class="form-group" action="{% url 'update.newjob' job.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

        <div class="container">
            <label for="id_title">عنوان:
                <input class="form-control" type="text" name="title" id="id_title" value="{{ job.title }}">
            </label>
            <br>
            <label for="id_name">نوع:
                <input class="form-control" type="text" name="type" id="id_name" value="{{ job.type }}">
            </label>
            <br>
            <label for="id_describe">مشخصات:
                <textarea class="form-control" type="text" name="background" id="id_describe">{{ job.background }}</textarea>
            </label>
            <br>
            <label for="id_price">قیمت:
                <input class="form-control" type="number" min="0" name="price" id="id_price" value="{{ job.price }}">
            </label>
            <br>
            <label for="id_image">عکس:
                <input class="form-control" type="file" name="image" id="id_image" value="{{ job.image }}">
            </label>
            <br>
            <input class="btn btn-success" type="submit" value="ثبت">
        </div>
    </form>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script defer src="{% static 'fontawesome/js/all.min.js' %}"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block content %}

{% endblock %}
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<footer class="text-center">© 2021 Coditors.com</footer>
</body>
</html>